; ============================================================
;  Mesa Balanceadora PID
;  ESP32-CAM / WROVER, OV2642) + PCA9685 + 2 servos
;  Framework: ESP-IDF puro
; ============================================================

[env:esp32cam]
platform         = espressif32
board            = esp32cam
framework        = espidf
monitor_speed    = 115200
upload_speed     = 460800

; Se der erro de board nao encontrado, troque por:
;   board = esp-wrover-kit
; ou descubra o seu com:  pio boards | grep -i wrover


board_build.partitions = partitions.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3   ; 0=nenhum 1=erro 2=warn 3=info 4=debug 5=verbose
